spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: "backend"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/test_db?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
    username: "root"
    password: "0000"
    hikari:
      idleTimeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      maxLifetime: 580000
  #    password: "ce19f003"
  jpa:
    database: "mysql"
    show-sql: "true"
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      schema-locations: classpath:scheme.sql
      data-locations: classpath:data.sql
      mode: always

#security:
#  basic:
#    enabled: false
project:
  properties:
    fcm_private_key_path: "oder-canvas-firebase-adminsdk-xeoff-b3e5bb9530.json"
    firebase-create-scoped: "https://www.googleapis.com/auth/firebase.messaging"
    firebase-multicast-message-size: 500
    imp-key: 1850902733988022
    imp-secret: c4f21589d46504d066a517cf34533f1944b8c109feac18988687e3795d6728556317d73b72860d74


# Cors properties
cors:
  # allowed-origins: 'localhost:3000,http://localhost,http://localhost:3000'
  allowed-origins: 'localhost:3000,http://localhost,http://localhost:3000,34.64.187.105:3000,http://34.64.187.105,http://34.64.187.105:3000,ws://34.64.187.105:3000,ws://34.64.187.105'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

server:
  servlet:
    session:
      cookie:
        http-only: false